### ISSUE TITLE
the expired session token is not handled gracefully

### ISSUE THREAD

**Issue by romange** [romange/helio#15]
here is what I get (redacted):

```
E20220924 22:13:38.256793 1244660 s3.cc:143] http error: HTTP/1.1 400 Bad Request
x-amz-request-id: BLA
x-amz-id-2: FOOO
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Sat, 24 Sep 2022 19:13:37 GMT
Server: AmazonS3
Connection: close

4ac
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0>TOKENFOOBAR</Token-0><RequestId>FOO</RequestId><HostId>BARR</HostId></Error>
0

F20220924 22:13:38.258005 1244659 s3_demo.cc:51] Check failed: list_res 
```

**Comment by romange** [comment]
it's ok for session tokens got via aws console but not ok when  the token was issued via instance role.

**Comment by dranikpg** [comment]
Makes sense, because we can only update it from the instance metadata without requesting any interaction from the library user. This would also require us to store where we got the data from.

**Comment by romange** [comment]
Maybe to store the role name? in that case you can know it's metadata and it will save you a hop next time.
